### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by fawzee94** [tom5454/Toms-Fabric-Lib#4]
Hey, this mod looks great and i'd love to try it out with other mods like simple drawers but my game crashes whenever i start it with the mod installed.
MultiMC log says this:

org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector shouldRenderDamageBar(Lnet/minecraft/class_1799;)Z in fabriclibs.hooks.mixins.json:ItemRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap toms-fabric-libs-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:516)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:413)
	at net.minecraft.client.main.Main.main(Main.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:516)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:413)
	at net.minecraft.client.main.Main.main(Main.java:135)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector shouldRenderDamageBar(Lnet/minecraft/class_1799;)Z in fabriclibs.hooks.mixins.json:ItemRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap toms-fabric-libs-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 30 more

**Comment by tom5454** [comment]
Can you send a full mod list?

**Comment by fawzee94** [comment]
Hi mate, sure no probs, ill do it as soon as I get back from work 👌

**Comment by fawzee94** [comment]
Hi there!

Here's the list of mods I have installed so far, the mod crashes with or
without tom's libs.


Please let me know if I can do anything else


Mods:

[✔️] [1.16.1][Fabric]+RPG-HUD-3.7.8

[✔️] 1.16.1-craftingstation-1.0.0

[✔️] advancements-enlarger-0.2.2

[✔️] antiqueatlas-5.3.0-fabric

[✔️] AppleSkin-mc1.16.1-forge-1.0.14

[✔️] artofalchemy-1.0.0-rc2+1.16.1

[✔️] autoswitch-2.7.1

[✔️] beenfo-1.16.1-forge32.0.38-1.1

[✔️] betterdroppeditems-1.2.1-1.16

[✔️] bettergraves-0.3.0

[✔️] bigbuckets-1.1.1

[✔️] campanion-1.1.13+build.35

[✔️] cavebiomes-0.2.4

[✔️] cinderscapes-1.0.7+build.43-1.16.1

[✔️] CleanView-1.16.1-v1-fabric

[✔️] conv-things-0.8.1-1.16.1

[✔️] cotton-1.0.5

[✔️] cotton-resources+unspecified-1.7.1

[✔️] Couplings-1.3.1

[✔️] crimson-moon-1.1.0-1.16

[✔️] dark-loading-screen-1.3.2

[✔️] DynamicSoundFilters-1.1.2+1.16.1

[✔️] easiercrafting-1.16-fabric0.13.1-1.6.1.beta5

[✔️] economical_villager_trading-0.9.1+1.16.1

[✔️] fabric-api-0.16.0+build.384-1.16.1

[✔️] fabric-language-kotlin-1.3.72+build.1

[✔️] fabric-tree-chopper-0.5.0

[✔️] flesh2leather-1.0.0

[✔️] golem-1.3.1

[✔️] golemsgalore-0.1.4+mc.1.16.1

[✔️] haema-1.1.3

[✔️] immersive-portals-0.20-mc1.16.1-fabric

[✔️] improved-stations-2.0.2-unstable

[✔️] inventoryprofiles-forge-1.16.1-0.4.2

[✔️] kibe-1.16.1-1.1.11-BETA

[✔️] makkit-1.0.2

[✔️] mcf-reap-1.4.0-1.16.1

[✔️] Mechanized-1.9.5

[✔️] Missing+Bits-v1.16.1+Fabric+b2

[✔️] modmenu-1.14.5+build.30

[✔️] MoEnchantments-1.12.2

[✔️] notes-1.16-1.0.1

[✔️] optifabric-1.1.0-beta2

[✔️] Origins-1.16-0.2.5

[✔️] paperdoll-1.0.4

[✔️] passable-leaves-1.2.0

[✔️] plantinajar-1.2.0+1.16.1

[✔️] PresenceFootsteps-r26+1.16-rc1

[✔️] preview_OptiFine_1.16.1_HD_U_G2_pre10

[✔️] quickshulker-1.1.5-1.16

[✔️] repairable-anvils-0.0.1

[✔️] respawnablepets-r3

[✔️] RingOfBlink-1.16.1-1.2.0

[✔️] RingOfEnderchest-Fabric-1.16.1-1.0.21

[✔️] RingOfGrowth-Fabric_1.16.1-1.0.19

[✔️] RingsOfAscension-1.16.1-1.0.3

[✔️] RoughlyEnoughItems-4.10.3

[✔️] sheepconsistency-1.0.2

[✔️] ShieldDisruptor-1.0.1-MC1.16.1

[✔️] Silky-Spawners-2.0.0+build.1-1.16

[✔️] simpledrawers-1.8.0-1.16.1

[✔️] simplexterrain-0.6.4

[✔️] strawdummy-1.1.0

[✔️] terrestria-2.0.4+build.50

[✔️] the_loved_ones-1.0.0+1.16.1

[✔️] TimeToLive-0.2

[❌] toms-fabric-libs-1.0.2.jar (disabled)

[❌] tomsstorage-1.1.1.jar (disabled)

[✔️] torchkey-1.0.3

[✔️] trapexpansion-1.3.2

[✔️] traverse-2.2.14+build.28

[✔️] trinkets-2.6.3

[✔️] unlimiteddragoneggs-1.0.0

[✔️] vanilla-hammers-1.10.1-1.16.1

[✔️] vanillautomated-1.1.2

[✔️] VarLightFabric-1.16-1.4.1

[✔️] verticalslabs-1.0.3

[✔️] winged-1.16-1.2

[✔️] Xaeros_Minimap_20.18.0_Fabric_1.16.1

[✔️] XaerosWorldMap_1.8.0_Fabric_1.16.1

**Comment by tom5454** [comment]
Please try it without optifabric installed.

**Comment by fawzee94** [comment]
Ok, it does work without optifabric, thanks! Does this mean that I can't have both?
